client-id: orario
client-secret: a6a1a667-b886-4fe2-81f1-5615ea227b56 # require for access_type: confidential
discovery-url: https://access-sso.apps.ocp4.rhocplab.com/auth/realms/peano
secure-cookie: false
skip-openid-provider-tls-verify: true
enable-default-deny: true
encryption-key: a6a1a667-b886-4fe2-81f1-5615ea227b56
listen: :8080
redirection-url: https://sec-fe-peano.apps.ocp4.rhocplab.com/
upstream-url: http://frontend:8080
resources:
- uri: /*
  methods:
  - GET
  - POST
  - PUT
  - DELETE
- uri: /index.html
  white-listed: true
- uri: /favicon
  white-listed: true
- uri: /css/*
  white-listed: true
- uri: /js/*
  white-listed: true
- uri: /img/*
  white-listed: true
- uri: /demo.html
  white-listed: true
- uri: /orario-demo.html
  white-listed: true
- uri: /rs/engine/2d71acaa-ddd9-4a38-aa02-34cfc51fb6a1
  white-listed: true
- uri: /rs/orario/2d71acaa-ddd9-4a38-aa02-34cfc51fb6a1
  white-listed: true
- uri: /rs/orario/check/2d71acaa-ddd9-4a38-aa02-34cfc51fb6a1
  white-listed: true