apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucchetto
  namespace: peano
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucchetto
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lucchetto
    spec:
      containers:
      - name: lucchetto
        image: quay.io/aleoncini/lucchetto:latest
        imagePullPolicy: Always
        command: 
        - /opt/louketo/louketo-proxy
        args:
        - --config
        - /etc/louketo/config.yaml
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - mountPath: /etc/louketo
            name: louketo-config
      restartPolicy: Always
      volumes:
        - name: louketo-config
          configMap:
            defaultMode: 420
            name: lucchetto-cm